# Generated by Django 2.2.1 on 2019-08-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_postingcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
