# Generated by Django 2.2.1 on 2019-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_posting_post_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingcomment',
            name='author',
            field=models.CharField(default=1, max_length=200, null=True),
        ),
    ]
