# Generated by Django 2.2.1 on 2019-08-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mediaboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default=1, max_length=200, null=True)),
                ('murl', models.CharField(max_length=200)),
                ('stan', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
