# Generated by Django 2.2.1 on 2019-08-07 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaboard',
            name='author',
            field=models.ForeignKey(default=1, null=True, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
