# Generated by Django 2.2.1 on 2019-08-03 06:05

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popkornApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='author',
            field=models.ForeignKey(default=1, null=True, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
