# Generated by Django 2.2.1 on 2019-07-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popkornApp', '0002_posting_postingcoment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postingcoment',
            old_name='post',
            new_name='posting',
        ),
    ]
